In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Employee_Attendance.csv')

In [4]:
df.head(5)

,EmpId,Date,Present,IsManual,InTime,OutTime,InDiff,OutDiff,IsLate,EarlyDeparture,MachineNo,IPAddress
0,E0001,2025-01-01,True,False,10:30:46,19:36:12,0.77,-23.80,True,True,M01,192.168.1.10
1,E0002,2025-01-01,True,False,10:41:24,20:08:55,11.40,8.92,True,False,M02,192.168.1.15
2,E0003,2025-01-01,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0004,2025-01-01,True,False,10:32:47,19:47:10,2.78,-12.83,True,True,M03,192.168.1.20
4,E0005,2025-01-01,True,False,10:30:47,19:42:42,0.78,-17.30,True,True,M03,192.168.1.20

In [5]:
df['IsManual'] = df['IsManual'].astype('boolean')

mask_out = df['Present'] & df['OutTime'].isna()
df.loc[mask_out, 'OutTime'] = '20:00:00'
df.loc[mask_out, 'IsManual'] = True
df.loc[mask_out, 'OutDiff'] = 0
df.loc[mask_out, 'EarlyDeparture'] = False


mask_in = df['Present'] & df['InTime'].isna()
df.loc[mask_in, 'InTime'] = '10:30:00'
df.loc[mask_in, 'IsManual'] = True
df.loc[mask_in, 'InDiff'] = 0
df.loc[mask_in, 'IsLate'] = False

In [8]:
import pandas as pd

expected_ip_map = {
    'M01': '192.168.1.10',
    'M03': '192.168.1.20',
    'M02': '192.168.1.15',
    'M04_HQ': '10.0.0.5'
}

df['ExpectedIP'] = df['MachineNo'].map(expected_ip_map)

invalid_rows = df[df['IPAddress'] != df['ExpectedIP']]

In [9]:
df = df[df['Present'] == True]

In [10]:
df

,EmpId,Date,Present,IsManual,InTime,OutTime,InDiff,OutDiff,IsLate,EarlyDeparture,MachineNo,IPAddress,ExpectedIP
0,E0001,2025-01-01,True,False,10:30:46,19:36:12,0.77,-23.80,True,True,M01,192.168.1.10,192.168.1.10
1,E0002,2025-01-01,True,False,10:41:24,20:08:55,11.40,8.92,True,False,M02,192.168.1.15,192.168.1.15
3,E0004,2025-01-01,True,False,10:32:47,19:47:10,2.78,-12.83,True,True,M03,192.168.1.20,192.168.1.20
4,E0005,2025-01-01,True,False,10:30:47,19:42:42,0.78,-17.30,True,True,M03,192.168.1.20,192.168.1.20
5,E0006,2025-01-01,True,False,10:43:49,20:20:40,13.82,20.67,True,False,M01,192.168.1.10,192.168.1.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,E0096,2025-05-20,True,False,13:25:53,22:46:54,175.88,166.90,True,False,M03,192.168.1.20,192.168.1.20
9996,E0097,2025-05-20,True,False,10:26:08,19:40:58,-3.87,-19.03,False,True,M03,192.168.1.20,192.168.1.20
9997,E0098,2025-05-20,True,False,10:23:41,16:20:01,-6.32,-219.98,False,True,M01,192.168.1.10,192.168.1.10
9998,E0099,2025-05-20,True,False,10:27:12,20:03:04,-2.80,3.07,False,False,M03,192.168.1.20,192.168.1.20
9999,E0100,2025-05-20,True,False,10:45:15,20:04:08,15.25,4.13,True,False,M02,192.168.1.15,192.168.1.15

In [11]:
df['InTime'] = pd.to_datetime(df['InTime'], format='%H:%M:%S', errors='coerce')
df['OutTime'] = pd.to_datetime(df['OutTime'], format='%H:%M:%S', errors='coerce')

target_in = pd.to_datetime('10:30:00', format='%H:%M:%S')
target_out = pd.to_datetime('20:00:00', format='%H:%M:%S')

filte_rows = df[

    (df['IsManual'] == True) &
    (df['InTime'] == target_in) &
    (df['OutTime'] == target_out)
]

In [13]:
filte_rows

,EmpId,Date,Present,IsManual,InTime,OutTime,InDiff,OutDiff,IsLate,EarlyDeparture,MachineNo,IPAddress,ExpectedIP
7,E0008,2025-01-01,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M01,192.168.1.10,192.168.1.10
223,E0024,2025-01-03,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M03,192.168.1.20,192.168.1.20
225,E0026,2025-01-03,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M02,192.168.1.15,192.168.1.15
309,E0010,2025-01-06,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M03,192.168.1.20,192.168.1.20
399,E0100,2025-01-06,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M02,192.168.1.15,192.168.1.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9308,E0009,2025-05-12,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M02,192.168.1.15,192.168.1.15
9519,E0020,2025-05-14,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M03,192.168.1.20,192.168.1.20
9852,E0053,2025-05-19,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M01,192.168.1.10,192.168.1.10
9874,E0075,2025-05-19,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M01,192.168.1.10,192.168.1.10
9959,E0060,2025-05-20,True,True,1900-01-01 10:30:00,1900-01-01 20:00:00,0.0,0.0,False,False,M01,192.168.1.10,192.168.1.10

In [14]:
df['row_id'] = df.index
filte_rows = df[
    (df['IsManual'] == True) &
    (df['InTime'] == target_in) &
    (df['OutTime'] == target_out)
].copy()

df['IsAnomaly'] = 0

df.loc[df['row_id'].isin(filte_rows['row_id']), 'IsAnomaly'] = 1

df.drop(columns='row_id', inplace=True)

In [15]:
df['IsAnomaly'].value_counts()

IsAnomaly
0    9229
1     128
Name: count, dtype: int64

In [18]:
df['InTime'] = pd.to_datetime(df['InTime'])
df['OutTime'] = pd.to_datetime(df['OutTime'])
df['InSeconds'] = df['InTime'].dt.hour * 3600 + df['InTime'].dt.minute * 60 + df['InTime'].dt.second
df['OutSeconds'] = df['OutTime'].dt.hour * 3600 + df['OutTime'].dt.minute * 60 + df['OutTime'].dt.second

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['EmpId'] = le.fit_transform(df['EmpId'])
df['Present'] = le.fit_transform(df['Present'])
df['IsManual'] = le.fit_transform(df['IsManual'])
df['MachineNo'] = le.fit_transform(df['MachineNo'])
df['IsLate'] = le.fit_transform(df['IsLate'])
df['EarlyDeparture'] = le.fit_transform(df['EarlyDeparture'])

In [20]:
df['Date'] = pd.to_datetime(df['Date'])

In [21]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [22]:
df.sample(2)

,EmpId,Date,Present,IsManual,InTime,OutTime,InDiff,OutDiff,IsLate,EarlyDeparture,MachineNo,IPAddress,ExpectedIP,IsAnomaly,InSeconds,OutSeconds,Year,Month,Day
6935,35,2025-04-08,0,0,1900-01-01 10:33:38,1900-01-01 20:12:26,3.63,12.43,1,0,0,192.168.1.10,192.168.1.10,0,38018,72746,2025,4,8
3312,12,2025-02-17,0,0,1900-01-01 10:38:43,1900-01-01 20:12:01,8.72,12.02,1,0,0,192.168.1.10,192.168.1.10,0,38323,72721,2025,2,17

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier

In [131]:
x = df[['EmpId', 'Present','IsManual', 'IsLate',	'EarlyDeparture', 'MachineNo',  'InSeconds', 'OutSeconds',  'Month', 'Day']]
y = df['IsAnomaly']

In [132]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [133]:
std = StandardScaler()
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)

In [134]:
x_train.shape

(7485, 10)

In [135]:
x_test.shape

(1872, 10)

In [136]:
smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

In [137]:
x_train_resampled.shape

(14766, 10)

In [138]:
y_train_resampled.shape

(14766,)

In [139]:
from collections import Counter

print("Before SMOTE:", Counter(y_train))
print("After SMOTE:", Counter(y_train_resampled))

Before SMOTE: Counter({0: 7383, 1: 102})
After SMOTE: Counter({0: 7383, 1: 7383})

In [140]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score

In [141]:
model = XGBClassifier(random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

In [142]:
model = XGBClassifier(random_state=42)
model.fit(x_train_resampled, y_train_resampled)

y_pred = model.predict(x_test)

In [162]:
print(accuracy_score(y_pred,y_test))

0.9989316239316239

In [143]:
model.score(x_test, y_test)

0.9989316239316239

In [144]:
model.score(x_train, y_train)

0.9998663994655979

In [145]:
model.score(x_train_resampled, y_train_resampled)

0.9999322768522281

In [146]:
confusion_matrix(y_test, y_pred)

array([[1844,    2],
       [   0,   26]])

In [147]:
scores = cross_val_score(model, x_train, y_train, cv=5)
print("CV Accuracy: ", scores.mean())

CV Accuracy:  0.9997327989311957

In [148]:
from sklearn.preprocessing import LabelEncoder

le_emp = LabelEncoder()
le_emp.fit(df['EmpId'])  # df is your original training DataFrame

le_machine = LabelEncoder()
le_machine.fit(df['MachineNo'])

LabelEncoder()

In [153]:
import pandas as pd

def get_user_input(le_emp, le_machine):
    emp_id = input("Enter EmpId: ").strip()
    machine_no = input("Enter MachineNo: ").strip()

    present = input("Enter Present (True/False): ").strip().lower() == 'true'
    is_manual = input("Enter IsManual (True/False): ").strip().lower() == 'true'
    is_late = input("Enter IsLate (True/False): ").strip().lower() == 'true'
    early_departure = input("Enter EarlyDeparture (True/False): ").strip().lower() == 'true'

    in_time = input("Enter InTime (HH:MM:SS): ").strip()
    out_time = input("Enter OutTime (HH:MM:SS): ").strip()

    month = int(input("Enter Month (1-12): ").strip())
    day = int(input("Enter Day (1-31): ").strip())

    def time_to_seconds(t):
        h, m, s = map(int, t.split(':'))
        return h * 3600 + m * 60 + s

    in_seconds = time_to_seconds(in_time)
    out_seconds = time_to_seconds(out_time)

    emp_id_encoded = le_emp.transform([emp_id])[0]
    machine_no_encoded = le_machine.transform([machine_no])[0]

    user_df = pd.DataFrame([{
        'EmpId': emp_id_encoded,
        'Present': int(present),
        'IsManual': int(is_manual),
        'IsLate': int(is_late),
        'EarlyDeparture': int(early_departure),
        'MachineNo': machine_no_encoded,
        'InSeconds': in_seconds,
        'OutSeconds': out_seconds,
        'Month': month,
        'Day': day
    }])

    return user_df
user_df = get_user_input(le_emp, le_machine)
print("User input dataframe:")
print(user_df)

prediction = model.predict(user_df)
print("Prediction (IsAnomaly):", int(prediction[0]))

Enter EmpId: 7
Enter MachineNo: 1
Enter Present (True/False): True
Enter IsManual (True/False): True
Enter IsLate (True/False): False
Enter EarlyDeparture (True/False): False
Enter InTime (HH:MM:SS): 10:30:00
Enter OutTime (HH:MM:SS): 20:00:00
Enter Month (1-12): 1
Enter Day (1-31): 1
User input dataframe:
   EmpId  Present  IsManual  IsLate  EarlyDeparture  MachineNo  InSeconds  \
0      7        1         1       0               0          1      37800

   OutSeconds  Month  Day
0       72000      1    1
Prediction (IsAnomaly): 0

In [62]:
from sklearn.ensemble import RandomForestClassifier

In [63]:
from sklearn.metrics import accuracy_score, classification_report

In [166]:
rf = RandomForestClassifier( class_weight='balanced',random_state=42)

In [167]:
rf.fit(x_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [168]:
y_pred = rf.predict(x_test)

In [169]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1846
           1       1.00      1.00      1.00        26

    accuracy                           1.00      1872
   macro avg       1.00      1.00      1.00      1872
weighted avg       1.00      1.00      1.00      1872

In [170]:
from sklearn.model_selection import GridSearchCV

In [171]:
param_grid = {
    'n_estimators': [2,3,5],
    'max_depth': [ 1,2,3],
    'min_samples_split': [3, 5, 10],
    'min_samples_leaf': [ 3, 4]

}

In [172]:
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid,
                           cv=5)

In [174]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_leaf': [3, 4],
                         'min_samples_split': [3, 5, 10],
                         'n_estimators': [2, 3, 5]})

In [175]:
print("Best Hyperparameters:", grid_search.best_params_)

Best Hyperparameters: {'max_depth': 3, 'min_samples_leaf': 3, 'min_samples_split': 3, 'n_estimators': 2}

In [176]:
y_pred=grid_search.predict(x_test)

In [177]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9962606837606838

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      1846
           1       0.79      1.00      0.88        26

    accuracy                           1.00      1872
   macro avg       0.89      1.00      0.94      1872
weighted avg       1.00      1.00      1.00      1872

In [205]:
from imblearn.over_sampling import RandomOverSampler

In [206]:
ros = RandomOverSampler(random_state=42)
x_resampled, y_resampled = ros.fit_resample(x, y)

print("Before resampling:")
print(y.value_counts())

print("\nAfter resampling:")
print(pd.Series(y_resampled).value_counts())

Before resampling:
IsAnomaly
0    9229
1     128
Name: count, dtype: int64

After resampling:
IsAnomaly
0    9229
1    9229
Name: count, dtype: int64

In [207]:
x_train, x_test, y_train, y_test = train_test_split(x_resampled, y_resampled, test_size=0.2, random_state=42)

mod = RandomForestClassifier(random_state=42)
mod.fit(x_train, y_train)

y_pred = mod.predict(x_test)

In [208]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1862
           1       1.00      1.00      1.00      1830

    accuracy                           1.00      3692
   macro avg       1.00      1.00      1.00      3692
weighted avg       1.00      1.00      1.00      3692

Confusion Matrix:
[[1861    1]
 [   0 1830]]

In [209]:
y_pred_real = model.predict(x)
print("Evaluation on original data:")
print(classification_report(y, y_pred_real))

Evaluation on original data:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9229
           1       0.99      1.00      1.00       128

    accuracy                           1.00      9357
   macro avg       1.00      1.00      1.00      9357
weighted avg       1.00      1.00      1.00      9357

In [195]:
from sklearn.preprocessing import LabelEncoder

le_emp = LabelEncoder()
le_machine = LabelEncoder()

# Fit on raw strings (e.g., 'E0001', 'M01')
le_emp.fit(df['EmpId'])
le_machine.fit(df['MachineNo'])

# Transform for model training
df['EmpId'] = le_emp.transform(df['EmpId'])
df['MachineNo'] = le_machine.transform(df['MachineNo'])

In [196]:
emp_id = int(input("Enter EmpId (0-99): "))
machine_no = int(input("Enter MachineNo (0-3): "))

Enter EmpId (0-99): 0
Enter MachineNo (0-3): 0

In [178]:

def get_user_input(le_emp, le_machine):
    emp_id = input("Enter EmpId: ").strip()
    machine_no = input("Enter MachineNo: ").strip()

    present = input("Enter Present (True/False): ").strip().lower() == 'true'
    is_manual = input("Enter IsManual (True/False): ").strip().lower() == 'true'
    is_late = input("Enter IsLate (True/False): ").strip().lower() == 'true'
    early_departure = input("Enter EarlyDeparture (True/False): ").strip().lower() == 'true'

    in_time = input("Enter InTime (HH:MM:SS): ").strip()
    out_time = input("Enter OutTime (HH:MM:SS): ").strip()

    month = int(input("Enter Month (1-12): ").strip())
    day = int(input("Enter Day (1-31): ").strip())

    def time_to_seconds(t):
        h, m, s = map(int, t.split(':'))
        return h * 3600 + m * 60 + s

    in_seconds = time_to_seconds(in_time)
    out_seconds = time_to_seconds(out_time)

    emp_id_encoded = le_emp.transform([emp_id])[0]
    machine_no_encoded = le_machine.transform([machine_no])[0]

    user_df = pd.DataFrame([{
        'EmpId': emp_id_encoded,
        'Present': int(present),
        'IsManual': int(is_manual),
        'IsLate': int(is_late),
        'EarlyDeparture': int(early_departure),
        'MachineNo': machine_no_encoded,
        'InSeconds': in_seconds,
        'OutSeconds': out_seconds,
        'Month': month,
        'Day': day
    }])

    return user_df

user_df = get_user_input(le_emp, le_machine)
print("User input dataframe:")
print(user_df)

prediction = grid_search.predict(user_df)
print("Prediction (IsAnomaly):", int(prediction[0]))

Enter EmpId: 8
Enter MachineNo: 1
Enter Present (True/False): True
Enter IsManual (True/False): True
Enter IsLate (True/False): False
Enter EarlyDeparture (True/False): False
Enter InTime (HH:MM:SS): 10:30:00
Enter OutTime (HH:MM:SS): 20:00:00
Enter Month (1-12): 1
Enter Day (1-31): 1
User input dataframe:
   EmpId  Present  IsManual  IsLate  EarlyDeparture  MachineNo  InSeconds  \
0      8        1         1       0               0          1      37800

   OutSeconds  Month  Day
0       72000      1    1
Prediction (IsAnomaly): 0

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [130]:
df['IsAnomaly']==1

0       False
1       False
3       False
4       False
5       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: IsAnomaly, Length: 9357, dtype: bool

In [ ]:
223	E0024	2025-01-03	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M03	192.168.1.20	192.168.1.20
225	E0026	2025-01-03	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M02	192.168.1.15	192.168.1.15
309	E0010	2025-01-06	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M03	192.168.1.20	192.168.1.20
399	E0100	2025-01-06	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M02	192.168.1.15	192.168.1.15
...	...	...	...	...	...	...	...	...	...	...	...	...	...
9308	E0009	2025-05-12	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M02	192.168.1.15	192.168.1.15
9519	E0020	2025-05-14	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M03	192.168.1.20	192.168.1.20
9852	E0053	2025-05-19	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M01	192.168.1.10	192.168.1.10
9874	E0075	2025-05-19	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M01	192.168.1.10	192.168.1.10
9959	E0060	2025-05-20	True	True	1900-01-01 10:30:00	1900-01-01 20:00:00	0.0	0.0	False	False	M01	192.168.1.10	192.168.1.10